### PR TITLE
Translated AllowToolStrings.xml into german

### PR DESCRIPTION
**Pull request by XNoNameX**
I translated it into german. It is 3.2.3. Hopefully everything is fine.

### CODE REVIEW

**Comment by XNoNameX** [comment]
And which do I also have to translate? Its a bit difficult to find the defs? Or was it everything? :)
Because when I look at the chinese translation there are some defs translated. But when I look into the defs which are not in the "Language" folder.. they are different. Is there a english version of everything? So I can pick that english version and just translate it from it? I am a bit confused, sorry. x)

**Comment by UnlimitedHugs** [comment]
Looks good, thanks. It'll be in the next update.
As for the defs, you can check out the Russian translation- it's fairly comprehensive. You could copy over the files and replace the text with your translation.

**Comment by XNoNameX** [comment]
I guess I have to understand russian if I have to translate its text.
Or did I understand it wrong :)

**Comment by UnlimitedHugs** [comment]
You don't need to- I was referring to the XML structure. You would have to look up the english text in the corresponding def file.
It's not ideal, but it should help.

**Pull request merged**
