### PR TITLE
Adding French translation

### PR DESCRIPTION
**Pull request by kaptain-kavern**

### CODE REVIEW

**Comment by kaptain-kavern** [comment]
Oh right. I had only checked the english folder

**Comment by kaptain-kavern** [comment]
I'm not that sure the new added files have been added here. But I've finished them.

Edit : Yes there are it seems. Tell me, if there is still problem please

**Comment by UnlimitedHugs** [comment]
Yep, that looks good to me.
As a heads-up, I'll be updating with a small addition tomorrow, so there will be minor changes.

**Comment by UnlimitedHugs** [comment]
Merged.

**Pull request closed without merging**
