### PR TITLE
updated german translation

### PR DESCRIPTION
**Pull request by lauri7x3**
updated german translation (now with definj files) https://drive.google.com/open?id=0B9BSE9s3xaQXajVfOXFXY1RlOXM

### CODE REVIEW

**Comment by UnlimitedHugs** [comment]
Not quite. You have to start your branch at 3.2.2 so that it can be cleanly applied on top of the master branch.

**Comment by lauri7x3** [comment]
oh dude, i have no idea of this side, of branches or anything else. u got the link...

**Comment by UnlimitedHugs** [comment]
Sorry, I stand for quality work. If you do, too, there can be no excuses.

**Comment by lauri7x3** [comment]
thats why i did the translation. still dont know whats the problem.

**Comment by UnlimitedHugs** [comment]
The pull request is conflicting with the master branch (i.e. the current working state of the project).
You'll have to read up on how to use GitHub and make proper pull request if you want to get this merged.

**Comment by UnlimitedHugs** [comment]
Closing, since a working translation was provided by another contributor.

**Pull request closed without merging**
