### PR TITLE
patch for v2.3.0

### PR DESCRIPTION
**Pull request by cainiaowu**

### CODE REVIEW

**Comment by cainiaowu** [comment]
Where can I find the HugsLib. mod setting string?

**Comment by UnlimitedHugs** [comment]
The settings strings are part of this library: https://github.com/UnlimitedHugs/RimworldHugsLib

**Comment by cainiaowu** [comment]
So it would be `HugsLib.HugsLib_settings_btn`, right?

**Comment by UnlimitedHugs** [comment]
The libraries language files are compiled directly into the dll- the proper way to do things would be to create a translation file in the library repo. Next time I update the library the new strings will appear in AllowTool and any other mods that use the library.

**Comment by cainiaowu** [comment]
Well, I will update them next time then.

**Comment by UnlimitedHugs** [comment]
Alright. Thank you for the translation.

**Pull request merged**
